# Generated by Django 5.2 on 2025-04-24 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="User", max_length=200, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "طالب"),
                            ("COORDINATOR", "منسق"),
                            ("ADMIN", "مشرف"),
                        ],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                (
                    "profile_img",
                    models.ImageField(
                        blank=True,
                        default="images/default.jpg",
                        null=True,
                        upload_to="images",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
