# Generated by Django 5.2 on 2025-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="sis_code",
            field=models.CharField(blank=True, null=True),
        ),
    ]
