# Generated by Django 5.2 on 2025-06-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_program_sis_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="university",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="users.university",
            ),
        ),
    ]
