# Generated by Django 5.2 on 2025-06-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="sis_add",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="programfee",
            name="is_requierd",
            field=models.BooleanField(default=False),
        ),
    ]
