# Generated by Django 5.2 on 2025-06-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0028_alter_form_academic_year"),
        ("coordination", "0002_academicyear_sis_add_alter_programfee_is_requierd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programfee",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="programfee",
            name="program",
        ),
        migrations.DeleteModel(
            name="AcademicYear",
        ),
        migrations.DeleteModel(
            name="ProgramFee",
        ),
    ]
