# Generated by Django 5.2 on 2025-05-07 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0019_alter_formsubmission_notes_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fee",
            name="submission_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="submission_id",
        ),
        migrations.AddField(
            model_name="fee",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="admissions.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="submission",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="admissions.formsubmission",
            ),
            preserve_default=False,
        ),
    ]
