# Generated by Django 5.2 on 2025-06-21 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_feestypes_feeslist"),
        ("users", "0006_academicyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_requierd", models.BooleanField(default=False)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_fees",
                        to="users.academicyear",
                    ),
                ),
                (
                    "fee_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_fees",
                        to="payments.feeslist",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_fees",
                        to="users.program",
                    ),
                ),
            ],
        ),
    ]
