# Generated by Django 5.2 on 2025-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_fee_submission_alter_order_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
