# Generated by Django 5.2 on 2025-05-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_order_is_paied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paied',
        ),
    ]
