# Generated by Django 5.2 on 2025-06-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_programfee_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="fees_list",
            field=models.ForeignKey(
                blank=True,
                default="95",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fees_fees_list",
                to="payments.programfee",
            ),
        ),
    ]
