# Generated by Django 5.2 on 2025-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0029_alter_form_academic_year"),
        ("payments", "0005_fee_fees_list"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fee",
            constraint=models.UniqueConstraint(
                fields=("submission", "fees_list"), name="unique_submission_fee_list"
            ),
        ),
    ]
