# Generated by Django 5.2 on 2025-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_fee_unique_submission_fee_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="fee_type",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
