# Generated by Django 5.2 on 2025-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_fee_fee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="fee_type",
            field=models.CharField(
                blank=True, default="initial", max_length=255, null=True
            ),
        ),
    ]
