# Generated by Django 5.2 on 2025-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_fee_created_at_fee_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
