# Generated by Django 5.2 on 2025-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
