# Generated by Django 5.2 on 2025-05-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_form_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="date_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="date_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="submissonsCount",
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="form",
            name="userSubmitCount",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
