# Generated by Django 5.2 on 2025-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admissions",
            "0003_form_date_end_form_date_start_form_submissonscount_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="text",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="title",
        ),
        migrations.AddField(
            model_name="option",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="section",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="tab",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
