# Generated by Django 5.2 on 2025-05-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admissions",
            "0004_rename_text_option_title_rename_text_question_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="question",
            name="option",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("select", "Dropdown"),
                    ("radio", "Multiple Choice"),
                    ("checkbox", "Checkboxes"),
                    ("date", "Date Picker"),
                    ("file-upload", "File Upload"),
                    ("number", "Number"),
                    ("multi-select", "Multi Select"),
                    ("draggable", "Draggable"),
                    ("payment", "Payment"),
                ],
                max_length=20,
            ),
        ),
    ]
