# Generated by Django 5.2 on 2025-05-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0005_question_config_question_option_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="option",
        ),
    ]
