# Generated by Django 5.2 on 2025-05-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0007_rename_config_question_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="modified_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
