# Generated by Django 5.2 on 2025-05-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0008_form_modified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="modified_at",
        ),
        migrations.AddField(
            model_name="form",
            name="modefied_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
