# Generated by Django 5.2 on 2025-05-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0009_remove_form_modified_at_form_modefied_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="modefied_at",
            new_name="modified_at",
        ),
    ]
