# Generated by Django 5.2 on 2025-05-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0010_rename_modefied_at_form_modified_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="question",
            new_name="question_id",
        ),
        migrations.RemoveField(
            model_name="form",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="form",
            name="date_start",
        ),
        migrations.RemoveField(
            model_name="form",
            name="description",
        ),
        migrations.RemoveField(
            model_name="form",
            name="submissonsCount",
        ),
        migrations.RemoveField(
            model_name="form",
            name="userSubmitCount",
        ),
        migrations.RemoveField(
            model_name="section",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tab",
            name="description",
        ),
        migrations.AddField(
            model_name="answer",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="form",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="option",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="section",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="tab",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
