# Generated by Django 5.2 on 2025-05-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0011_rename_question_answer_question_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="section",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tab",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
