# Generated by Django 5.2 on 2025-05-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0012_question_is_archived_section_is_archived_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="question_id",
            new_name="question",
        ),
    ]
