# Generated by Django 5.2 on 2025-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0013_rename_question_id_answer_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="option",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
