# Generated by Django 5.2 on 2025-05-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0014_formsubmission_is_archived_option_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="meta_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
