# Generated by Django 5.2 on 2025-05-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0015_question_meta_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
