# Generated by Django 5.2 on 2025-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0016_formsubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
