# Generated by Django 5.2 on 2025-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_formsubmission_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="notes",
            field=models.TextField(blank=True, default="تحت المراجعة", null=True),
        ),
    ]
