# Generated by Django 5.2 on 2025-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0018_alter_formsubmission_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "تحت المراجعة"),
                    ("accepted", "تم القبول"),
                    ("rejected", "تم الرفض"),
                    ("noted", "توجد ملاحظات"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
