# Generated by Django 5.2 on 2025-05-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_alter_formsubmission_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
