# Generated by Django 5.2 on 2025-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_form_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='is_paied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
