# Generated by Django 5.2 on 2025-06-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0022_formsubmission_is_paied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("reviewed", "مستوفي"),
                    ("pending", "تحت المراجعة"),
                    ("accepted", "تم القبول"),
                    ("rejected", "تم الرفض"),
                    ("noted", "توجد ملاحظات"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
