# Generated by Django 5.2 on 2025-06-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0023_alter_formsubmission_status"),
        ("coordination", "0002_academicyear_sis_add_alter_programfee_is_requierd"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="syear",
            field=models.ForeignKey(
                blank=True,
                default="1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="syear",
                to="coordination.academicyear",
            ),
        ),
    ]
