# Generated by Django 5.2 on 2025-06-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0024_form_syear"),
        ("coordination", "0002_academicyear_sis_add_alter_programfee_is_requierd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form",
            name="syear",
        ),
        migrations.AddField(
            model_name="form",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                default="1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_year",
                to="coordination.academicyear",
            ),
        ),
    ]
