# Generated by Django 5.2 on 2025-06-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0025_remove_form_syear_form_academic_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="is_paied_collage",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
