# Generated by Django 5.2 on 2025-06-20 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0026_formsubmission_is_paied_collage"),
        ("users", "0005_alter_faculty_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="program",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program",
                to="users.program",
            ),
        ),
    ]
