# Generated by Django 5.2 on 2025-06-21 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0028_alter_form_academic_year"),
        ("users", "0006_academicyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_year",
                to="users.academicyear",
            ),
        ),
    ]
